### ISSUE TITLE
explain permissions requested by app

### ISSUE THREAD

**Issue by bclozel** [ahmadnassri/app-restconsole#32]
Could you explain why this application requests those permissions?
- Your data on all websites (medium alert)
- Your tabs and browsing activity (low alert)

A short word on the chrome webstore description page should be great!

**Comment by ahmadnassri** [comment]
this is a question asked by everybody using chrome apps, and a pain for everybody building them.

I'll start with the easiest one:
- **Your tabs and browsing activity** 
  - Google explanation: Required if the extension uses the chrome.tabs or chrome.windows module.
  - What we use it for: the only access to tabs we need is for launching the oAuth Authorization page to the 3rd party oAuth provider.
- **Your data on all websites**
  - Google Explanation: Specifies a host permission. Required if the extension wants to create cross-origin XMLHttpRequests, and the cookies API require host permissions.
  - What we use it for: we ask for `*://*/*` so that developers can make API calls to ANY URL ... 

we don't collect any personal data, we don't want access to your data on all websites, I personally don't agree with Google's labeling this permission as "Your data on all websites" its confusing to average users ... however we're dealing with developers and it should be simple enough for any developer to understand how this works and to know that we only ask for these permissions to give the developer access, not us.

do you think the above description is clear enough to be posted on the webstore, or does it require more clarity?

thanks.

**Comment by bclozel** [comment]
I know rest-console targets developers, and as a developer myself I'm more than enclined to check out the code.
But I've come across several weird permission changes and [strange behaviors](http://www.seroundtable.com/google-amazon-treatment-13881.html) in chrome apps.

I think this description fits well and should definitely be posted on the webstore, especially if you plan to change permissions in the future.

Many thanks for this great app.

**Comment by ahmadnassri** [comment]
I've changed the permissions for the "extension" as I completely changed the whole of it to become a launcher for the "App"
I don't think I'll ever change permissions for the App, unless google comes up with a new API or some better permissions for the App's purpose ...

I will post this description to the store right now.

thanks for your feedback.
