### ISSUE TITLE
Parameters are not being sent when executing POST

### ISSUE THREAD

**Issue by gabehayes** [ahmadnassri/app-restconsole#47]
This seems odd, but I can't seem to figure out what's happening.  I know it's not my code, because the API is still functioning normally when sending requests with both Authorization header and as Querystring.

When sending the request as a GET using Authorization header, all parameters are collected:

<pre>
object(sfParameterHolder)#31 (1) {
  ["parameters":protected]=>
  array(10) {
    ["username"]=>
    string(4) "myun"
    ["password"]=>
    string(4) "mypw"
    ["module"]=>
    string(4) "v1_0"
    ["action"]=>
    string(14) "authorizeLogin"
    ["oauth_signature_method"]=>
    string(9) "HMAC-SHA1"
    ["oauth_version"]=>
    string(3) "1.0"
    ["oauth_nonce"]=>
    string(5) "Zne77"
    ["oauth_timestamp"]=>
    string(10) "1317847018"
    ["oauth_consumer_key"]=>
    string(15) "my_consumer_key"
    ["oauth_signature"]=>
    string(30) "OtiCKSapvIPjBNFtCwu6hvfuVoI%3D"
  }
}
</pre>

**The breakdown**:
    + username/password are sent as _Request Parameters_ under the _Request Payload_ section.
    + module/action are request parameters set by Symfony Framework
    + my controller code grabs the apache headers and adds all of the oauth parameters to the request object

When sending the request as a POST using Authorization header, _Request Parameters_ are missing:

<pre>
object(sfParameterHolder)#31 (1) {
  ["parameters":protected]=>
  array(8) {
    ["module"]=>
    string(4) "v1_0"
    ["action"]=>
    string(14) "authorizeLogin"
    ["oauth_signature_method"]=>
    string(9) "HMAC-SHA1"
    ["oauth_version"]=>
    string(3) "1.0"
    ["oauth_nonce"]=>
    string(5) "Zne77"
    ["oauth_timestamp"]=>
    string(10) "1317847018"
    ["oauth_consumer_key"]=>
    string(15) "my_consumer_key"
    ["oauth_signature"]=>
    string(30) "OtiCKSapvIPjBNFtCwu6hvfuVoI%3D"
  }
}
</pre>

This happens when using Authorization and Querystring.  For whatever reason, when POSTing, whatever is in the _Request Parameters_ section is not being passed.

**Comment by ahmadnassri** [comment]
the request payload **IS** being posted, but you are not setting the Body's `Content-Type` header ... or you are setting the wrong `Content-Type` header.

(I'm almost 99.9% certain this is the issue since I've been asked this all week, plz stop reading if that's not the case and let me know otherwise)

PHP (and other languages) expects the `Content-Type` header to be set to `application/x-www-form-urlencoded` so it would parse this string `username=myun&password=mypw` into a $_POST variable ... (and subsequently get picked up by Symphony and any other Framework as request parameters)

while this is a "typical" behavior for sending data through HTML forms, its not limiting, you can send a payload of `username=myun&password=mypw` and tell the server its `application/xml` if you wish ... its up to the client library to determine what to set the `Content-Type` header to, and to the server to determine how interpret the request body as, based on the `Content-Type` header it receives ...

in the previous version I had set that field to be set to `application/x-www-form-urlencoded` by default, since most of the time that is the case, but in this version I left everything bare so that the developer can decide where to start.

I thought it wasn't an issue, but based on how many people have complained about POST data not being sent, maybe I'll make it pre-populated again, but a little background info doesn't hurt ...

**Comment by gabehayes** [comment]
That definitely did the trick...sorry for the troubles
