### ISSUE TITLE
can't fetch raw body from request

### ISSUE THREAD

**Issue by ghost** [ahmadnassri/app-restconsole#51]
Hi, I'm testing the restful service built with zend using rest-console. I have set the GET Request Payload - Raw Body as something like '{"locationId":"33","limit":"5","offset":"0"}', I have set content type for Accept and Content Headers to 'application/json'. But when I fetch the request body in Zend using '$payload = $this->getRequest()->getRawBody();', it return null. Please help. Thank you in advance.

**Comment by ghost** [comment]
when I print out the `$this->getRequest();`, it's like below: 

``` php
object(Zend_Controller_Request_Http) #60 (15) {
  ["_paramSources":protected]= > array(2) {
    [0] = > string(4)"_GET" [1] = > string(5)"_POST"
}["_requestUri": protected] = > string(10)"/api/review" ["_baseUrl": protected] = > string(0)"" ["_basePath": protected] = > NULL["_pathInfo": protected] = > string(11)"/api/review" ["_params": protected] = > array(3) {
    ["module"] = > string(3)"api" ["controller"] = > string(6)"review" ["action"] = > string(5)"index"
}["_rawBody": protected] = > NULL["_aliases": protected] = > array(0) {}["_dispatched": protected] = > bool(true)["_module": protected] = > string(3)"api" ["_moduleKey": protected] = > string(6)"module" ["_controller": protected] = > string(6)"review" ["_controllerKey": protected] = > string(10)"controller" ["_action": protected] = > string(5)"index" ["_actionKey": protected] = > string(6)"action"
}
```

The '_rawBody' field is null. However, I have tested it from command line using 

``` bash
curl -v -H "Content-Type: application/json" -X GET -d "{\"locationId\":\"33\",\"limit\":\"5\",\"offset\":\"0\"}" http://localhost/api/review
```

and it return data correctly. Why is it like this. Please help. :'(

**Comment by ahmadnassri** [comment]
I suspect this is a issue on the server side, not in REST Console, to quickly confirm, just check your Chrome Developer Tools and look under Network -> XHR to see what's actually being sent.

from my experience with Zend/PHP you gotta be careful with using the `getRawBody()` call since it basically just calls: `file_get_contents('php://input')` which can only be done once, if you do it twice, you get a null on the second call.

also, for some reason that I still don't get, Zend doesn't retain the value in the protected variable `$_rawBody` on the request object, so if you call `getRawBody()` more than once, the expected behaviour is to read `php://input` the first time and store the result internally ... but that doesn't happen.

make sure your code (or Zend Framework) is not calling `getRawBody()` somewhere else which would clear out the `phpt://input`

if you do find that REST Console is not sending your data let me know, but I would check Zend first, as I also use Zend for all my server side development and I do send JSON data all the time and it works for me.

**Comment by ahmadnassri** [comment]
also, on a separate note, checkout PHP's [HTTP extension](http://php.net/manual/en/book.http.php), it made my life so much easier in managing HTTP requests:

**Comment by ghost** [comment]
Hi, thank you for the reply. Below is the request I got from the XHR, I don't see the request body.

```
Request URL:http://localhost/api/review
Request Method:GET
Status Code:400 Bad Request
Request Headersview source
Accept:application/json
Accept-Charset:UTF-8,*;q=0.5
Accept-Encoding:gzip,deflate,sdch
Accept-Language:en,fi;q=0.8,zh-CN;q=0.6
Connection:keep-alive
Content-Type:application/json
Cookie:ZDEDebuggerPresent=php,phtml,php3
Host:localhost
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/14.0.835.202 Safari/535.1
Response Headersview source
Connection:close
Content-Type:application/json
Date:Wed, 12 Oct 2011 18:13:43 GMT
Server:Apache/2.2.16 (Win32) mod_ssl/2.2.16 OpenSSL/0.9.8o
Set-Cookie:ZDEDebuggerPresent=php,phtml,php3; path=/
Transfer-Encoding:chunked
X-Powered-By:PHP/5.3.5 ZendServer
```

However, when I make the POST request, I can get the Request Payload:

```
Request URL:http://localhost/api/review
Request Method:POST
Status Code:400 Bad Request
Request Headersview source
Accept:application/json
Accept-Charset:UTF-8,*;q=0.5
Accept-Encoding:gzip,deflate,sdch
Accept-Language:en,fi;q=0.8,zh-CN;q=0.6
Connection:keep-alive
Content-Length:44
Content-Type:application/json
Cookie:ZDEDebuggerPresent=php,phtml,php3
Host:localhost
Origin:chrome-extension://cokgbflfommojglbmbpenpphppikmonn
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/14.0.835.202 Safari/535.1
Request Payload
{"locationId":"33","limit":"5","offset":"0"}
Response Headersview source
Connection:close
Content-Type:application/json
Date:Wed, 12 Oct 2011 18:15:18 GMT
Server:Apache/2.2.16 (Win32) mod_ssl/2.2.16 OpenSSL/0.9.8o
Set-Cookie:ZDEDebuggerPresent=php,phtml,php3; path=/
Transfer-Encoding:chunked
X-Powered-By:PHP/5.3.5 ZendServer
```

Does it mean anything? By the way, the request from command works fine, so I guess the code works fine. Also, I have only one place in the controller action that invoke getRawBody().
Thanks.

**Comment by ahmadnassri** [comment]
Yes, you cannot send a request payload with a GET request ... Only POST, PUT, DELETE and few others ...

Refer to [RFC 2616](http://www.ietf.org/rfc/rfc2616.txt)

**Comment by ahmadnassri** [comment]
just to clarify, does it work with POST?

**Comment by ghost** [comment]
Yes, the POST works fine. But I'm wondering why the command woks even if it's GET request: 

``` bash
curl -v -H "Content-Type: application/json" -X GET -d "{\"locationId\":\"33\",\"limit\":\"5\",\"offset\":\"0\"}" http://localhost/api/review 
```

So I should parse the payload like `http://localhost/api/review?payload={\"locationId\":\"33\",\"limit\":\"5\",\"offset\":\"0\"}` for GET request and parse raw body only for POST, PUT, DELETE requests?

What if I also use `http://localhost/api/review?payload={...}` for POST, PUT and DELETE without parsing raw body? Is it a good practice or any better way? (hope you don't mind that I ask many questions)

**Comment by ahmadnassri** [comment]
it isn't explicitly forbidden to send a body payload with GET as per the HTTP specification, when you are doing it in curl, you're basically forcing whatever you want on the server.

so while you can do that, I would suggest avoiding it simply because people (and machines) don't expect expect that. 

There are many phases in an HTTP request chain and while they "mostly" conform to the HTTP spec, the only thing you're assured is that they will behave as traditionally used by web browsers. (I'm thinking of things like transparent proxies, accelerators, A/V toolkits, etc.)

I'm wondering why you are trying to do that through GET as oppose to using POST?

its always a good practice to send your data payload as POST / PUT and leave GET for just query strings (though you can use a combination of query strings with POST / PUT as well)

ex: 

``` bash
curl -v -H "Content-Type: application/json" -X POST -d "{\"locationId\":\"33\",\"limit\":\"5\",\"offset\":\"0\"}" http://localhost/api/review?key=value&display=true
```

**Comment by ahmadnassri** [comment]
further to my point about "what people and machines expect" there is an un-spoken tradition of just following what a browser would do in building HTTP libraries ...

so always think: "What would a browser do?" (WWBD) ... or better yet, "What would Chrome Do?" (WWCD) 

:)

**Comment by ghost** [comment]
Thank you very much. For the GET request, I meant http://localhost/api/review?filter={\"locationId\":\"33\",\"limit\":\"5\",\"offset\":\"0\"}
